version: '3.7'

services:
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile
    depends_on:
      - catalogdb
  
  catalogdb:
    image: mongo

volumes:
  mongo_data: 
